# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/advanced_conf.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(323, 229)
        Dialog.setStyleSheet("background-color:#353535;\n" "color:white;\n" "")
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setObjectName("formLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.subset_size = QtWidgets.QSpinBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subset_size.sizePolicy().hasHeightForWidth())
        self.subset_size.setSizePolicy(sizePolicy)
        self.subset_size.setObjectName("subset_size")
        self.gridLayout.addWidget(self.subset_size, 5, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 4, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 0, 1, 1)
        self.batch_size = QtWidgets.QSpinBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batch_size.sizePolicy().hasHeightForWidth())
        self.batch_size.setSizePolicy(sizePolicy)
        self.batch_size.setObjectName("batch_size")
        self.gridLayout.addWidget(self.batch_size, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 3, 0, 1, 1)
        self.query_mode = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.query_mode.sizePolicy().hasHeightForWidth())
        self.query_mode.setSizePolicy(sizePolicy)
        self.query_mode.setObjectName("query_mode")
        self.gridLayout.addWidget(self.query_mode, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.performance_thresh = QtWidgets.QSlider(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.performance_thresh.sizePolicy().hasHeightForWidth()
        )
        self.performance_thresh.setSizePolicy(sizePolicy)
        self.performance_thresh.setMaximum(100)
        self.performance_thresh.setSingleStep(1)
        self.performance_thresh.setOrientation(QtCore.Qt.Horizontal)
        self.performance_thresh.setObjectName("performance_thresh")
        self.gridLayout.addWidget(
            self.performance_thresh, 4, 1, 1, 1, QtCore.Qt.AlignHCenter
        )
        self.ok = QtWidgets.QPushButton(Dialog)
        self.ok.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok.sizePolicy().hasHeightForWidth())
        self.ok.setSizePolicy(sizePolicy)
        self.ok.setObjectName("ok")
        self.gridLayout.addWidget(self.ok, 6, 1, 1, 1)
        self.epochs = QtWidgets.QSpinBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.epochs.sizePolicy().hasHeightForWidth())
        self.epochs.setSizePolicy(sizePolicy)
        self.epochs.setObjectName("epochs")
        self.gridLayout.addWidget(self.epochs, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.gridLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_14.setText(_translate("Dialog", "Performance Threshold"))
        self.label_10.setText(_translate("Dialog", "Training Epochs"))
        self.label_12.setText(_translate("Dialog", "Subset Size"))
        self.label_11.setText(_translate("Dialog", "Training Batch Size"))
        self.label_13.setText(_translate("Dialog", "Query Mode"))
        self.ok.setText(_translate("Dialog", "OK"))
