FROM continuumio/miniconda3
RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y
COPY .. .
RUN conda env create -f environment.yml
SHELL ["conda", "run", "-n", "mlada", "/bin/bash", "-c"] 
RUN conda install pytorch torchvision -c pytorch